const places = [
  {
    id: "1",
    name: "Nike Mercurial Superfly 9",
    description: "Elite performance boot for speed",
    price: 275,
    imageSrc: "/placeholder-product.svg",
    href: "#",
    rating: 4.8,
    ratingCount: 124,
  },
  {
    id: "2",
    name: "Adidas Predator Accuracy+",
    description: "Precision control boot",
    price: 300,
    imageSrc: "/placeholder-product.svg",
    href: "#",
    rating: 4.7,
    ratingCount: 98,
  },
  {
    id: "3",
    name: "Puma Future Ultimate",
    description: "Agility and ball control",
    price: 220,
    imageSrc: "/placeholder-product.svg",
    href: "#",
    rating: 4.6,
    ratingCount: 87,
  },
  {
    id: "4",
    name: "New Balance Tekela v4",
    description: "Comfort meets performance",
    price: 180,
    imageSrc: "/placeholder-product.svg",
    href: "#",
    rating: 4.5,
    ratingCount: 65,
  },
  {
    id: "5",
    name: "Mizuno Morelia Neo III",
    description: "Classic leather boot",
    price: 240,
    imageSrc: "/placeholder-product.svg",
    href: "#",
    rating: 4.9,
    ratingCount: 156,
  },
];

export default places;
