export const PRODUCT_CATEGORIES = {
  JERSEYS: "JERSEYS",
  BOOTS: "BOOTS",
  FOOTBALLS: "FOOTBALLS",
  TRADING_CARDS: "TRADING_CARDS",
  GOALKEEPER_GLOVES: "GOALKEEPER_GLOVES",
  SHIN_GUARDS: "SHIN_GUARDS",
  TRAINING_EQUIPMENT: "TRAINING_EQUIPMENT",
  ACCESSORIES: "ACCESSORIES",
} as const;

export type ProductCategoryType =
  (typeof PRODUCT_CATEGORIES)[keyof typeof PRODUCT_CATEGORIES];

// Popular brands for the marketplace
export const POPULAR_BRANDS = [
  "Nike",
  "Adidas",
  "Jordan",
  "Yeezy",
  "Supreme",
  "Off-White",
  "Balenciaga",
  "Louis Vuitton",
  "Gucci",
  "Prada",
  "Dior",
  "Hermès",
  "Rolex",
  "Audemars Piguet",
  "Patek Philippe",
  "Cartier",
  "Chrome Hearts",
  "Rick Owens",
  "Fear of God",
  "Stone Island",
  "Moncler",
  "Canada Goose",
  "The North Face",
  "Arc'teryx",
  "BAPE",
  "Palace",
  "Stüssy",
  "Kith",
  "Comme des Garçons",
  "Acne Studios",
];

// Size ranges for different product types
export const SIZE_RANGES = {
  SHOES_US_MEN: [
    "4",
    "4.5",
    "5",
    "5.5",
    "6",
    "6.5",
    "7",
    "7.5",
    "8",
    "8.5",
    "9",
    "9.5",
    "10",
    "10.5",
    "11",
    "11.5",
    "12",
    "12.5",
    "13",
    "14",
    "15",
  ],
  SHOES_US_WOMEN: [
    "5",
    "5.5",
    "6",
    "6.5",
    "7",
    "7.5",
    "8",
    "8.5",
    "9",
    "9.5",
    "10",
    "10.5",
    "11",
    "11.5",
    "12",
  ],
  CLOTHING: ["XXS", "XS", "S", "M", "L", "XL", "XXL", "XXXL"],
  CLOTHING_NUMERIC: [
    "36",
    "38",
    "40",
    "42",
    "44",
    "46",
    "48",
    "50",
    "52",
    "54",
    "56",
  ],
  RING_SIZES: [
    "3",
    "3.5",
    "4",
    "4.5",
    "5",
    "5.5",
    "6",
    "6.5",
    "7",
    "7.5",
    "8",
    "8.5",
    "9",
    "9.5",
    "10",
    "10.5",
    "11",
    "11.5",
    "12",
    "12.5",
    "13",
  ],
  WATCH_SIZES: [
    "36mm",
    "38mm",
    "40mm",
    "41mm",
    "42mm",
    "44mm",
    "45mm",
    "46mm",
    "47mm",
    "48mm",
  ],
};

// Authentication methods
export const AUTHENTICATION_METHODS = [
  "In-house authentication",
  "Brand authentication",
  "Third-party authentication (e.g., StockX, GOAT)",
  "Receipt/proof of purchase",
  "Serial number verification",
];
