ALTER TABLE "order" ADD COLUMN IF NOT EXISTS "easypostShipmentId" TEXT;
ALTER TABLE "order" ADD COLUMN IF NOT EXISTS "labelUrl" TEXT;
ALTER TABLE "order" ADD COLUMN IF NOT EXISTS "labelTrackingNumber" TEXT;
ALTER TABLE "order" ADD COLUMN IF NOT EXISTS "labelCarrier" TEXT;
ALTER TABLE "order" ADD COLUMN IF NOT EXISTS "labelBoughtAt" TIMESTAMPTZ;
